# Generated by Django 5.1.1 on 2024-10-02 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('trading_networks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='employees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='сотрудник'),
        ),
        migrations.AddField(
            model_name='network',
            name='products',
            field=models.ManyToManyField(to='products.product', verbose_name='продукт'),
        ),
        migrations.AddField(
            model_name='network',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_networks', to='trading_networks.network', verbose_name='поставщик'),
        ),
    ]
