# Generated by Django 5.1.1 on 2024-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_networks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network_name',
            field=models.CharField(max_length=50, verbose_name='название сети'),
        ),
    ]
