# Generated by Django 5.1.1 on 2024-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(max_length=25, verbose_name='модель продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=25, verbose_name='название продукта'),
        ),
    ]
